<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "soee_cookiecuttr"
 *
 * Auto generated by Extension Builder 2013-12-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'soee - CookieCuttr',
    'description' => 'This extension implements jQuery based CookieCuttr plugin to present cookie law message. For more details visit http://cookiecuttr.com/',
    'category' => 'fe',
    'author' => 'Marcin Sągol',
    'author_email' => 'kontakt@soee.pl',
    'author_company' => 'soee.pl',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '1.0.0',
    'constraints' => array(
        'depends' => array(
            'extbase' => '6.0',
            'fluid' => '6.0',
            'typo3' => '6.0-6.2.99',
            'vhs' => '1.5.0',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);

?>